### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by zoejonestx91** [Xiphoseer/htmlcars#1]
Hi,

Is this released under any license? I was hoping to be able to create a DM screen app for Star Trek Adventures using htmlcars.

Thank you!

**Comment by Xiphoseer** [comment]
Hey,

thanks for asking! The IP to the Star Trek brand is owned by CBS studios, and they have used that to take down a commercial app in the past. That means I can't grant a full commercial license, even if I wanted to.

However, I absolutely do want to license the projects source code under a permissive open-source license. This has not been decided yet, but this issue is a good time to do just that. What do you think of the [Mozilla Public License 2.0](https://choosealicense.com/licenses/mpl-2.0/)?

Finally, the LCARS font used in the project is covered by a custom license similar to [CC BY-NC-ND](https://creativecommons.org/licenses/by-nc-nd/4.0/). The original german license is:
> die hier angebotenen Schriftfonts LCARS GTJ2.ttf und LCARS GTJ3.ttf sind freeware. Das heißt, du darfst sie kostenlos herunterladen und überall verwenden, wo du möchtest. Allerdings dürfen die Dateien nicht umbenannt, verändert oder verkauft werden. Die Schriftdateien sind Programmintern mit einem eindeutigen Copyrightvermerk versehen, die GTJLCARS.de als Urheber kennzeichnet.

which specifies that the files may not be renamed, modified, or sold and the files contain an attribution to the author.

**Comment by zoejonestx91** [comment]
Hi,

Yeah, my plans were to make the GM screen app as being under an open source license, but I hadn't decided which one, and for simplicity's sake was just going to follow your lead. MPL2 would work well for me.

As for the LCARS font, their license is pretty much what I was hoping for.

Also, how would you like to be credited?

On an unrelated note, I want to say you've done great work. ^^

**Comment by Xiphoseer** [comment]
Hey, thank you for your feedback. I'll go through and add the appropriate licensing information this week, if I find the time. As for giving credit, a link to <https://xiphoseer.github.io/htmlcars> would be great (and should qualify as notifying your users where to get the source as per MPL2). Also, if your project is hosted/pulished somwhere please do send me a link so I can include it on the docs.

**Comment by Xiphoseer** [comment]
Closed with 05d2a607740e7bf0d5f71e0b025869475391a7ec
